version: '3.7'
services:
  message-broker:
    image: duhon/php:7.3-fpm
    hostname: app
    ports:
      - "22:22"
    stop_signal: SIGKILL
    working_dir: /var/www/catalog-storefront
    volumes:
      - .:/var/www/catalog-storefront
      - ./dev/tools/install_message_broker.sh:/var/www/catalog-storefront/install_message_broker.sh
    environment:
      COMPOSER_HOME: /var/www/.composer
      BACKOFFICE_URL: http://host.docker.internal/
    command: sh install_message_broker.sh
    x-setup:
    x-info: https://devdocs.magento.com/
networks:
  default:
    driver: bridge
